import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/Nav ";
import Footer from "@/components/Footer ";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-black min-h-screen flex flex-col justify-between ">
          <Nav />

        <main className="flex-grow flex flex-col items-center justify-center px-4 py-8 sm:px-6 md:px-8 lg:px-16">
        {children}
      </main>
        {/* {children} */}
        <Footer />
        </div>
      </body>
    </html>
  );
}
